include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    always_specify_types: error
    prefer_final_parameters: error
    require_trailing_commas: error
    sort_pub_dependencies: error
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"

linter:
  rules:
    - always_specify_types
    - prefer_final_parameters
    - require_trailing_commas
    - sort_pub_dependencies
