name: goddchen_cv
description: CV and portfolio for Martin "Goddchen" Liersch
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=3.10.6 <4.0.0"

dependencies:
  dio: ^5.3.2
  easy_image_viewer: ^1.2.1
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.6
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.7
  fpdart: ^0.6.0
  freezed_annotation: ^2.4.1
  go_router: ^10.0.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  retrofit: ^4.0.1
  riverpod_annotation: ^2.1.1
  url_launcher: ^6.1.12

dev_dependencies:
  build_runner: ^2.4.6
  flutter_flavorizr: ^2.2.1
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: 2.3.5
  mockito: ^5.4.2
  retrofit_generator: 7.0.2
  riverpod_generator: 2.2.3

flutter:
  assets:
    - assets/icons/github/
    - assets/icons/youtube/
    - assets/images/hobbies/igp/
    - assets/images/youtube/
  uses-material-design: true

flutter_gen:
  integrations:
    flutter_svg: true
