name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          flutter-version: "3.10.6"
      - run: flutter build web -t lib/main_production.dart --web-renderer html
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          channelId: live
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_GODDCHEN_CV }}"
          projectId: goddchen-cv
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          target: goddchen-cv
