jobs:
  flutter_package:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_version: "3.10.6"
      min_coverage: 0
      runs_on: "ubuntu-22.04"
  semantic_pull_request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1
name: Pull Requests
on: pull_request
